version: 2.1

jobs:
  download_ccache:
    name: download ccache
    container:
      image: jk8s/cirrus-ci-aosp:latest
      cpu: 8
      memory: 32G
    steps:
      - run:
          name: download ccache
          command: ./download_ccache

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - download_ccache
