version: 2.1

jobs:
  download_ccache:
    name: download ccache
    container:
      image: jk8s/cirrus-ci-aosp:latest
      cpu: 8
      memory: 32G
    steps:
      - run:
          name: download ccache
          command: ./download_ccache

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - download_ccache

jobs:
  download_ccache:
    environment:
        CIRRUS_CLONE_DEPTH: 1
        CIRRUS_WORKING_DIR: "/tmp/ci"
        rclone_config: "ENCRYPTED[f98850b20879fcbd16836a3cbedefdeb57289777d7eaa36ccafc270e9d3667b79187135d950b596f39d9f7504df84c49]"