
version: 2.1

jobs:
  build:
    docker:
      - image: apon77/aosp:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Download ccache
          command:  #!/bin/bash
                  df -h
                  free -h
                  nproc
                  cat /etc/os*
                  env
                  url=https://rombuildersimp.vvs-didi.workers.dev/ccache/ci2/ccache.tar.gz
                  cd /tmp
                  time aria2c $url -x16 -s50
                  time tar xf ccache.tar.gz
                  rm -rf ccache.tar.gz
      - run:
          name: Sync source
          command: sync
      - run:
          name: Monitor background
          command: monitor
      - run:
          name: Build
          command: build
      - run:
          name: Upload ccache
          command: upload_ccache
workflows:
  version: 2
  build:
    jobs:
      - build